import type { Metadata } from "next";
import "../styles/globals.scss";
import Footer from "./components/footer/page";
import Header from "./components/header/page";
import { CartProvider } from "./components/cartContext/page";
import { SearchProvider } from "./components/searchContext/page";
import { WishlistProvider } from "./components/wishlistContext/page";

export const metadata: Metadata = {
  title: "Gymbeast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <SearchProvider>
            <WishlistProvider>
              <Header />
              {children}
              <Footer />
            </WishlistProvider>
          </SearchProvider>
        </CartProvider>
      </body>
    </html>
  );
}
