
"use client"

import { usePathname } from 'next/navigation'; 
import type { Metadata } from "next";
import "../styles/globals.scss";
import Footer from "./components/footer/page";
import Header from "./components/header/page";
import { CartProvider } from "./components/cartContext/page";
import { SearchProvider } from "./components/searchContext/page";
import { WishlistProvider } from "./components/wishlistContext/page";

//  export const metadata: Metadata = {
//   title: "Gymbeast",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();

  const isLoginPage = pathname === '/login'

  return (
    <html lang="en">
      <body>
        <CartProvider>
          <SearchProvider>
            <WishlistProvider>
              {!isLoginPage && <Header />}
              {children}
              {!isLoginPage && <Footer />}
            </WishlistProvider>
          </SearchProvider>
        </CartProvider>
      </body>
    </html>
  );
}
